-- Checkpoint 4 introduces the executable ingestion schema without rewriting the prior migration.
-- IDs are generated by the application so no PostgreSQL extension is required.
CREATE TABLE IF NOT EXISTS products (
  id TEXT PRIMARY KEY,
  product_key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  framework TEXT NOT NULL,
  report_format TEXT NOT NULL,
  freshness_target_hours INTEGER NOT NULL CHECK (freshness_target_hours > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS test_executions (
  id TEXT PRIMARY KEY,
  product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  base_key TEXT NOT NULL UNIQUE,
  identity_key TEXT NOT NULL UNIQUE,
  content_hash TEXT NOT NULL,
  report_format TEXT NOT NULL,
  source TEXT NOT NULL,
  origin TEXT NOT NULL CHECK (origin IN ('SEEDED_DEMO', 'DEMO_PIPELINE')),
  suite_type TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('PASSED', 'FAILED', 'SKIPPED', 'ERROR', 'NOT_EXECUTED')),
  total INTEGER NOT NULL CHECK (total >= 0),
  executed INTEGER NOT NULL CHECK (executed >= 0),
  passed INTEGER NOT NULL CHECK (passed >= 0),
  failed INTEGER NOT NULL CHECK (failed >= 0),
  skipped INTEGER NOT NULL CHECK (skipped >= 0),
  errors INTEGER NOT NULL CHECK (errors >= 0),
  duration_ms INTEGER NOT NULL CHECK (duration_ms >= 0),
  approval_rate DOUBLE PRECISION,
  quality_score DOUBLE PRECISION,
  infrastructure_error JSONB,
  artifact_path TEXT,
  regression_delta JSONB NOT NULL DEFAULT '{"newFailures":0,"recovered":0,"persistentFailures":0,"newTests":0,"removedTests":0}'::jsonb,
  started_at TIMESTAMPTZ NOT NULL,
  finished_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS test_executions_product_created_idx
  ON test_executions(product_id, created_at DESC);

CREATE TABLE IF NOT EXISTS pipeline_metadata (
  id TEXT PRIMARY KEY,
  execution_id TEXT NOT NULL UNIQUE REFERENCES test_executions(id) ON DELETE CASCADE,
  branch TEXT NOT NULL,
  commit_sha TEXT NOT NULL,
  pipeline_id TEXT,
  pipeline_url TEXT,
  job_id TEXT,
  job_name TEXT NOT NULL,
  job_url TEXT,
  artifact_url TEXT,
  environment TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS test_suites (
  id TEXT PRIMARY KEY,
  execution_id TEXT NOT NULL REFERENCES test_executions(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  status TEXT NOT NULL,
  total INTEGER NOT NULL,
  executed INTEGER NOT NULL,
  passed INTEGER NOT NULL,
  failed INTEGER NOT NULL,
  skipped INTEGER NOT NULL,
  errors INTEGER NOT NULL,
  position INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS test_case_results (
  id TEXT PRIMARY KEY,
  suite_id TEXT NOT NULL REFERENCES test_suites(id) ON DELETE CASCADE,
  stable_key TEXT NOT NULL,
  framework TEXT NOT NULL,
  file_path TEXT NOT NULL,
  suite_path JSONB NOT NULL,
  title TEXT NOT NULL,
  status TEXT NOT NULL,
  duration_ms INTEGER NOT NULL,
  error_type TEXT,
  error_message TEXT,
  expected_value TEXT,
  actual_value TEXT,
  sanitized_stack TEXT,
  position INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS test_case_results_stable_key_idx ON test_case_results(stable_key);

CREATE TABLE IF NOT EXISTS integration_tokens (
  id TEXT PRIMARY KEY,
  product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  token_prefix TEXT NOT NULL,
  token_hash TEXT NOT NULL,
  salt TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  revoked_at TIMESTAMPTZ,
  rotated_from_id TEXT REFERENCES integration_tokens(id)
);

CREATE INDEX IF NOT EXISTS integration_tokens_product_active_idx
  ON integration_tokens(product_id, revoked_at);

CREATE TABLE IF NOT EXISTS demo_runs (
  id TEXT PRIMARY KEY,
  product_key TEXT NOT NULL,
  suite_type TEXT NOT NULL,
  mode TEXT NOT NULL,
  state TEXT NOT NULL,
  progress_message TEXT NOT NULL,
  execution_id TEXT REFERENCES test_executions(id),
  error_message TEXT,
  artifact_path TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  started_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ
);
